import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';
import '@/styles/globals.css';
import { MusicProvider } from '@/components/musicplayer/music-context'; // Sesuaikan path
import MusicPlayer from '@/components/musicplayer/musicplayer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MusicProvider>
          {/* Music Player akan muncul di semua halaman */}
          <MusicPlayer />

          {/* Konten halaman */}
          {children}
        </MusicProvider>
      </body>
    </html>
  );
}
